### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by cryptaliagy** [DudeRandom21/Stop-uOttawa-Surveillance#6]
Nous sommes une université bilingue, so we need to ensure that the petition is available in both English and French. 

This could be done by using a cookie so it persists between sessions, but will require a cookie statement banner if we do so.

**Comment by cryptaliagy** [comment]
Per discussions we will be doing this by extracting the browser language

**Comment by t0xicCode** [comment]
FYI, you likely don't need a cookie banner to store the language preference as it is a first-party, non-tracking, technical cookie required to enable user-requested functionality. It is sufficient to specify that you may store that cookie in the privacy policy (maybe under a _Cookie Policy_ header).
